Subscribe lecture button fixes #197
MaMpf-HD/mampf pull request #215
Opened 2021-01-16 12:04 UTC by henrixapp

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature

* **Please check if the PR fulfills these requirements**

- [x] E2E Tests for the changes have been added  via Cypress

* **What is the current behavior?** (You can also link to an open issue here)

#197 

* **What is the new behavior (if this is a feature change)?**

You can try to subscribe on to a lecture on its page.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No.

* **Other information**:

2021-01-20 10:06 UTC, henrixapp commented
http_caching issue must be resolved.

2021-01-27 09:47 UTC, fosterfarrell9 requested changes

2021-01-27 09:47 UTC, fosterfarrell9 commented on app/models/ability.rb
> +           :display_course, :subscribe_page], Lecture
This does the trick only for generic users. The corresponding rules should also be added to admins/editors/teachers (their rulesets are some lines above in the other parts of the `if` block).

2021-01-27 09:47 UTC, fosterfarrell9 commented on app/controllers/profile_controller.rb
> +    p(@lecture)
This can be removed :-)

2021-01-27 09:47 UTC, fosterfarrell9 commented on config/locales/en.yml
> +    not_subscribed: You are currently not subscribed to this course.
It should be "You are currently not subscribed to this lecture".

2021-01-27 09:47 UTC, fosterfarrell9 commented on config/locales/de.yml
> +    not_subscribed: Du bist zur Zeit nicht in dieser Vorlesung AbonnentIn.
I would suggest some rewording like "Aktuell hast Du diese Veranstaltung nicht abonniert."

2021-01-27 10:35 UTC, fosterfarrell9 requested changes
The availability of this feature for editors and teachers has yet to be added, is does not work for them as of now: see the comment in the last feature. The reason ist that a `can :subscribe_page, Lecture` is missing for them in `ability.rb` (without that, they are redirected to main with the usual error message).

2021-01-28 18:25 UTC, fosterfarrell9 approved these changes

2021-01-28 19:39 UTC, merged