added xkcd back without gem dependency
MaMpf-HD/mampf pull request #376
Opened 2022-03-17 01:11 UTC by zebleck

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **Please check if the PR fulfills these requirements**

- [ ] E2E Tests for the changes have been added  via Cypress
- [ ] Meaningful rspec tests have been added
- [ ] Docs have been added / updated 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-04-04 15:19 UTC, fosterfarrell9 requested changes

2022-04-04 15:19 UTC, fosterfarrell9 commented on app/models/xkcd.rb
> +class Xkcd < ApplicationRecord
This class does not need to inherit from `ApplicationRecord`, it should be a plain Ruby class:

`class Xkcd`

2022-04-04 15:19 UTC, fosterfarrell9 commented on app/models/xkcd.rb
> +    JSON.parse(URI.open("https://xkcd.com/#{comic_num}/info.0.json").read)
Maybe we could add some `rescue` statement here in order to catch an exception when the `URI.open`  method returns an error, e.g. when the xkcd site is down/not responding for some reason.

2022-04-20 14:07 UTC, zebleck commented
requests fixed

2022-04-30 16:14 UTC, merged