Fix comment status
MaMpf-HD/mampf pull request #585
Opened 2024-01-08 16:48 UTC by Splines

Fixes #573.

See discussion on #574 for further details.
Previous PR for this was #576, closed in favor of this one as this directly branches off the new "dev" branch.

2024-01-09 17:33 UTC, fosterfarrell9 requested changes

2024-01-09 17:33 UTC, fosterfarrell9 commented on app/models/user.rb
> +      next unless comments
`comments` is an array, and empty arrays are truthy in Ruby. You might want to replace this by 

```ruby
next if comments.blank?
```

2024-01-09 17:33 UTC, fosterfarrell9 commented on app/models/user.rb
> +      next unless comments_not_by_creator
Same here. You might want to replace this by 

```ruby
next if comments_not_by_creator.blank?
```

2024-01-09 17:33 UTC, fosterfarrell9 commented on app/controllers/readers_controller.rb
>      end
In some later PR, the code duplication in `main_controller.rb` and `readers_controller.rb` should be removed, e.g. by writing a method for the last two lines.

2024-01-10 17:35 UTC, fosterfarrell9 approved these changes

2024-01-11 18:09 UTC, Splines commented
thanks for the approval. I will merge once the respective migration is ready

2024-01-16 18:15 UTC, merged