Policy/course editor change only for admins
MaMpf-HD/mampf pull request #610
Opened 2024-04-07 10:11 UTC by fosterfarrell9

Only admins can update the editors of a course, the course editors themselves can't do this. Until now, this was a little inconsequentially only realized in the view by leaving out the corresponding form. This PR whitelists the `editor_ids` parameter only for admins and adds a helpdesk.

2024-04-08 16:06 UTC, Splines requested changes

2024-04-08 16:06 UTC, Splines commented on app/controllers/courses_controller.rb
> +                          division_ids: [] }]
This wasn't grouped together beforehand, but now you use `{` `}` to define one hash? Or how is the `{` working in this case?

Furthermore, maybe put these three params in one line, they nicely (almost) fit the 80 chars width.

2024-04-08 16:06 UTC, Splines commented on config/locales/de.yml
> +          ModuleditoInnen können nur von AdministratorInnen geändert werden.
typo: ModuleditorInnen

2024-04-08 16:06 UTC, Splines commented on config/locales/en.yml
> +          Please contact %{project_email} by email if want a change to be made
typo: missing `you` (if *you* want a change to be made)

2024-04-08 16:06 UTC, Splines commented on app/controllers/courses_controller.rb
In this file, there's also a method `search_params` where we allow an array of `editor_ids` to be passed in. Do we need a change there as well?

2024-04-08 16:49 UTC, fosterfarrell9 commented on app/controllers/courses_controller.rb
> +                          division_ids: [] }]
It is enforced by rubocop, see [https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem](here).
But they are definitely not necessary in l103.

2024-04-08 16:54 UTC, fosterfarrell9 commented on app/controllers/courses_controller.rb
No, this is only used for searching courses (accesible to non-generic users) in `administration/search` and here the data can (and should) be visible.

2024-04-08 17:08 UTC, Splines commented on app/controllers/courses_controller.rb
> +                          division_ids: [] }]
ah ok thanks, good to know

2024-04-08 17:14 UTC, Splines requested changes

2024-04-08 17:14 UTC, Splines commented on app/views/courses/_basics.html.erb
> +                   project_email: mail_to(DefaultSetting::PROJECT_EMAIL, nil)),
`name=nil` is the [default](https://apidock.com/rails/ActionView/Helpers/UrlHelper/mail_to), so no need to specify it here explicitly.

2024-04-09 10:46 UTC, Splines approved these changes

2024-04-09 17:24 UTC, merged