Init `just` as command-line runner
MaMpf-HD/mampf pull request #660
Opened 2024-07-03 22:03 UTC by Splines

2024-07-04 12:42 UTC, Splines commented on .vscode/extensions.json
> +        "nefrob.vscode-just-syntax"
Feel free to install that recommended extension ;)

2024-07-09 12:37 UTC, fosterfarrell9 requested changes
Works nicely. Just one question: Is there a wiki page on just in our wiki? I could not find one, but it would be really helpful.

2024-07-09 13:06 UTC, Splines commented
I've added a section about how to install Just [here in the Wiki](https://github.com/MaMpf-HD/mampf/wiki/Installation-&-Setup#setting-up-your-workspace-as-a-dev-team-member). However, you're right it might be better to have a separate section for it for quick reference. I can then reference that section on the installation page.

2024-07-10 13:02 UTC, Splines commented
I've outsourced the section to [this new section](https://github.com/MaMpf-HD/mampf/wiki/Installation-&-Setup#installation-of-just-command-line-runner) explaining how to install/update `just`.

2024-08-01 10:43 UTC, fosterfarrell9 approved these changes

2024-08-01 10:48 UTC, Splines commented
Note you can now run `yarn just-update` and should get the version `1.33.0`. In this version, modules are stabilized 🙌

2024-08-01 11:00 UTC, merged