Fix lecture edit page if active term is not set
MaMpf-HD/mampf pull request #683
Opened 2024-08-20 17:17 UTC by fosterfarrell9

This fixes #682 by adding the missing case in the `older_than?` method in the `Lecture` model.

2024-08-20 17:52 UTC, Splines requested changes
LGTM.

- Maybe you can add an end-to-end test to ensure that the lecture#edit page looks as expected? (instead of showing an error?)
- And maybe even add a unit test for the `lecture.stale?` method to ensure it gives proper results even in the case where we just have a lecture and not an active term set.

2024-08-20 18:56 UTC, fosterfarrell9 commented
I added unit tests for `lecture#stale?`, made `lecture#older_than?` private (it is not used anywhere except by the lecture#stale? method) and added a cypress test for the lecture edit page that should fail when the page throws an error.

2024-08-21 14:14 UTC, Splines requested changes

2024-08-21 14:14 UTC, Splines commented on spec/cypress/e2e/lecture_spec.cy.js
> +    });
```suggestion
    cy.createUserAndLogin("teacher").then((teacher) => {
      FactoryBot.create("lecture", "with_teacher_by_id",
        { teacher_id: teacher.id }).as("lecture");
    });
```

2024-08-21 14:14 UTC, Splines commented on spec/cypress/e2e/lecture_spec.cy.js
> +      cy.getBySelector("content-tab-btn").should("be.visible");
LGTM, this will definitely fail if the page throws an error ;)

2024-08-21 14:14 UTC, Splines commented on app/models/lecture.rb
>    def stale?
Maybe one last thing: could you add a docstring including an explanation for what "stale" means? (doesn't have to include every detail, just a high-level overview maybe)

2024-08-21 14:14 UTC, Splines commented on spec/models/lecture_spec.rb
> +      let(:year) { 2024 }
```suggestion
```

2024-08-21 14:17 UTC, Splines requested changes

2024-08-21 14:17 UTC, Splines commented on spec/models/lecture_spec.rb
> +    let(:year) { 2024 }
```suggestion
```

2024-08-21 14:21 UTC, Splines requested changes

2024-08-21 14:21 UTC, Splines commented on spec/cypress/e2e/lecture_spec.cy.js
rename to `lectures_spec.cy.js` (plural) to be consistent with other cypress spec files

2024-08-21 14:52 UTC, fosterfarrell9 commented on spec/cypress/e2e/lecture_spec.cy.js
Thanks for catching this!

2024-08-21 17:28 UTC, Splines approved these changes
LGTM. Note that you'll have to approve the tests such that they can run through before merging via `Squash and merge`.

2024-08-21 17:35 UTC, fosterfarrell9 commented
run tests

2024-08-21 17:44 UTC, merged